//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Atom.proto
namespace Senseix.Message.Atom
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Atom")]
  public partial class Atom : global::ProtoBuf.IExtensible
  {
    public Atom() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private Senseix.Message.Atom.Atom.Type _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Senseix.Message.Atom.Atom.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private bool _required;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"required", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool required
    {
      get { return _required; }
      set { _required = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEXT", Value=0)]
      TEXT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMAGE", Value=1)]
      IMAGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUDIO", Value=2)]
      AUDIO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIDEO", Value=3)]
      VIDEO = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}