//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Categories.proto
namespace Senseix.Message.Categories
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticsData")]
  public partial class StatisticsData : global::ProtoBuf.IExtensible
  {
    public StatisticsData() {}
    
    private uint _time_played;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time_played", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_played
    {
      get { return _time_played; }
      set { _time_played = value; }
    }
    private uint _percentage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"percentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint percentage
    {
      get { return _percentage; }
      set { _percentage = value; }
    }
    private uint _correct;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"correct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint correct
    {
      get { return _correct; }
      set { _correct = value; }
    }
    private uint _answered;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"answered", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint answered
    {
      get { return _answered; }
      set { _answered = value; }
    }
    private uint _mastery;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mastery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mastery
    {
      get { return _mastery; }
      set { _mastery = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeSeriesStatsData")]
  public partial class TimeSeriesStatsData : global::ProtoBuf.IExtensible
  {
    public TimeSeriesStatsData() {}
    
    private string _day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string day
    {
      get { return _day; }
      set { _day = value; }
    }
    private Senseix.Message.Categories.StatisticsData _stats;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Categories.StatisticsData stats
    {
      get { return _stats; }
      set { _stats = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticsGetResponse")]
  public partial class StatisticsGetResponse : global::ProtoBuf.IExtensible
  {
    public StatisticsGetResponse() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _parent_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"parent_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> parent_ids
    {
      get { return _parent_ids; }
    }
  
    private Senseix.Message.Categories.StatisticsData _statistics;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"statistics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Categories.StatisticsData statistics
    {
      get { return _statistics; }
      set { _statistics = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CategoriesGetResponse")]
  public partial class CategoriesGetResponse : global::ProtoBuf.IExtensible
  {
    public CategoriesGetResponse() {}
    
    private readonly global::System.Collections.Generic.List<string> _category_ids = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"category_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> category_ids
    {
      get { return _category_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeSeriesGetResponse")]
  public partial class TimeSeriesGetResponse : global::ProtoBuf.IExtensible
  {
    public TimeSeriesGetResponse() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<Senseix.Message.Categories.TimeSeriesStatsData> _series = new global::System.Collections.Generic.List<Senseix.Message.Categories.TimeSeriesStatsData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"series", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Categories.TimeSeriesStatsData> series
    {
      get { return _series; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}