//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Device.proto
namespace Senseix.Message.Device
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeviceRegistrationRequest")]
  public partial class DeviceRegistrationRequest : global::ProtoBuf.IExtensible
  {
    public DeviceRegistrationRequest() {}
    
    private string _device_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _information;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"information", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string information
    {
      get { return _information; }
      set { _information = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeviceRegistrationResponse")]
  public partial class DeviceRegistrationResponse : global::ProtoBuf.IExtensible
  {
    public DeviceRegistrationResponse() {}
    
    private string _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _is_temporary_account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_temporary_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_temporary_account
    {
      get { return _is_temporary_account; }
      set { _is_temporary_account = value; }
    }
    private string _auth_token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"auth_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string auth_token
    {
      get { return _auth_token; }
      set { _auth_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameVerificationRequest")]
  public partial class GameVerificationRequest : global::ProtoBuf.IExtensible
  {
    public GameVerificationRequest() {}
    
    private string _udid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _verification_token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"verification_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string verification_token
    {
      get { return _verification_token; }
      set { _verification_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameVerificationResponse")]
  public partial class GameVerificationResponse : global::ProtoBuf.IExtensible
  {
    public GameVerificationResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}