//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Leaderboard.proto
namespace Senseix.Message.Leaderboard
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberData")]
  public partial class MemberData : global::ProtoBuf.IExtensible
  {
    public MemberData() {}
    
    private string _player_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerData")]
  public partial class PlayerData : global::ProtoBuf.IExtensible
  {
    public PlayerData() {}
    
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayerScoreRequest")]
  public partial class UpdatePlayerScoreRequest : global::ProtoBuf.IExtensible
  {
    public UpdatePlayerScoreRequest() {}
    
    private string _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _player_score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_score
    {
      get { return _player_score; }
      set { _player_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayerScoreResponse")]
  public partial class UpdatePlayerScoreResponse : global::ProtoBuf.IExtensible
  {
    public UpdatePlayerScoreResponse() {}
    
    private uint _total_members;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"total_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_members
    {
      get { return _total_members; }
      set { _total_members = value; }
    }
    private Senseix.Message.Leaderboard.PlayerData _player;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Leaderboard.PlayerData player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRankRequest")]
  public partial class PlayerRankRequest : global::ProtoBuf.IExtensible
  {
    public PlayerRankRequest() {}
    
    private string _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _page_size = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"page_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint page_size
    {
      get { return _page_size; }
      set { _page_size = value; }
    }
    private Senseix.Message.Leaderboard.SortBy _sort_by = Senseix.Message.Leaderboard.SortBy.NONE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sort_by", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Senseix.Message.Leaderboard.SortBy.NONE)]
    public Senseix.Message.Leaderboard.SortBy sort_by
    {
      get { return _sort_by; }
      set { _sort_by = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRankResponse")]
  public partial class PlayerRankResponse : global::ProtoBuf.IExtensible
  {
    public PlayerRankResponse() {}
    
    private uint _total_members;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"total_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_members
    {
      get { return _total_members; }
      set { _total_members = value; }
    }
    private readonly global::System.Collections.Generic.List<Senseix.Message.Leaderboard.PlayerData> _player = new global::System.Collections.Generic.List<Senseix.Message.Leaderboard.PlayerData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Leaderboard.PlayerData> player
    {
      get { return _player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SortBy")]
    public enum SortBy
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK", Value=1)]
      RANK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE", Value=2)]
      SCORE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=3)]
      NONE = 3
    }
  
}