//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Problem.proto
// Note: requires additional types generated from: Atom.proto
namespace Senseix.Message.Problem
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Formatter")]
  public partial class Formatter : global::ProtoBuf.IExtensible
  {
    public Formatter() {}
    
    private string _html = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"html", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string html
    {
      get { return _html; }
      set { _html = value; }
    }
    private string _css = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"css", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string css
    {
      get { return _css; }
      set { _css = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Question")]
  public partial class Question : global::ProtoBuf.IExtensible
  {
    public Question() {}
    
    private readonly global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> _atom = new global::System.Collections.Generic.List<Senseix.Message.Atom.Atom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"atom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> atom
    {
      get { return _atom; }
    }
  
    private Senseix.Message.Problem.Formatter _format = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"format", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Senseix.Message.Problem.Formatter format
    {
      get { return _format; }
      set { _format = value; }
    }
    private byte[] _image = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image
    {
      get { return _image; }
      set { _image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Answer")]
  public partial class Answer : global::ProtoBuf.IExtensible
  {
    public Answer() {}
    
    private readonly global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> _atom = new global::System.Collections.Generic.List<Senseix.Message.Atom.Atom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"atom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> atom
    {
      get { return _atom; }
    }
  
    private Senseix.Message.Problem.Formatter _format = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"format", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Senseix.Message.Problem.Formatter format
    {
      get { return _format; }
      set { _format = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Distractor")]
  public partial class Distractor : global::ProtoBuf.IExtensible
  {
    public Distractor() {}
    
    private readonly global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> _atom = new global::System.Collections.Generic.List<Senseix.Message.Atom.Atom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"atom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Atom.Atom> atom
    {
      get { return _atom; }
    }
  
    private Senseix.Message.Problem.Formatter _format = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"format", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Senseix.Message.Problem.Formatter format
    {
      get { return _format; }
      set { _format = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemData")]
  public partial class ProblemData : global::ProtoBuf.IExtensible
  {
    public ProblemData() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private Senseix.Message.Problem.Question _question;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"question", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Problem.Question question
    {
      get { return _question; }
      set { _question = value; }
    }
    private Senseix.Message.Problem.Answer _answer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"answer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Problem.Answer answer
    {
      get { return _answer; }
      set { _answer = value; }
    }
    private Senseix.Message.Problem.Distractor _distractor;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"distractor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Senseix.Message.Problem.Distractor distractor
    {
      get { return _distractor; }
      set { _distractor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnswerIdentifier")]
  public partial class AnswerIdentifier : global::ProtoBuf.IExtensible
  {
    public AnswerIdentifier() {}
    
    private readonly global::System.Collections.Generic.List<string> _uuid = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> uuid
    {
      get { return _uuid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemPost")]
  public partial class ProblemPost : global::ProtoBuf.IExtensible
  {
    public ProblemPost() {}
    
    private string _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _problem_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"problem_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string problem_id
    {
      get { return _problem_id; }
      set { _problem_id = value; }
    }
    private Senseix.Message.Problem.AnswerIdentifier _answer_ids = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"answer_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Senseix.Message.Problem.AnswerIdentifier answer_ids
    {
      get { return _answer_ids; }
      set { _answer_ids = value; }
    }
    private float _duration = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private bool _skipped = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skipped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool skipped
    {
      get { return _skipped; }
      set { _skipped = value; }
    }
    private bool _correct = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"correct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool correct
    {
      get { return _correct; }
      set { _correct = value; }
    }
    private ulong _answered_at_unix_time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"answered_at_unix_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong answered_at_unix_time
    {
      get { return _answered_at_unix_time; }
      set { _answered_at_unix_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemPostRequest")]
  public partial class ProblemPostRequest : global::ProtoBuf.IExtensible
  {
    public ProblemPostRequest() {}
    
    private readonly global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemPost> _problem = new global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemPost>();
    [global::ProtoBuf.ProtoMember(1, Name=@"problem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemPost> problem
    {
      get { return _problem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemPostResponse")]
  public partial class ProblemPostResponse : global::ProtoBuf.IExtensible
  {
    public ProblemPostResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemGetRequest")]
  public partial class ProblemGetRequest : global::ProtoBuf.IExtensible
  {
    public ProblemGetRequest() {}
    
    private string _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _problem_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"problem_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint problem_count
    {
      get { return _problem_count; }
      set { _problem_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProblemGetResponse")]
  public partial class ProblemGetResponse : global::ProtoBuf.IExtensible
  {
    public ProblemGetResponse() {}
    
    private readonly global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemData> _problem = new global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"problem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Senseix.Message.Problem.ProblemData> problem
    {
      get { return _problem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}